#!/bin/bash
#mount /dev/Files/root /mnt

setfont ter-u18b.psf.gz -m 8859-2
echo "console font set."

iwctl station wlan0 scan
iwctl station wlan0 get-networks
iwctl station wlan0 connect SK_WiFiGIGAD61C_5G
echo "wifi connected."

pacman -Sy neovim pbzip2 git curl
echo "neovim, pbzip2, git, curl installed."

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "vim-plug installed."
cd
mkdir -p .config/nvim
cd .config/nvim
git clone https://github.com/createsejin/nvimt .
echo "nvimt git cloned."

timedatectl set-ntp true
timedatectl set-timezone Asia/Seoul
echo "timezone set."

echo "Finding fastest mirror server lists."
echo "This job take a lot of time. Wait for finish."
reflector -c "South Korea" -a 12 --sort rate \
--save /etc/pacman.d/mirrorlist
echo "Job finished."

echo -e "All jobs done. \u25A0"
