general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follows_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: false

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "0px"

  # Gap between windows and the screen edge.
  outer_gap: "0px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#0000ff"

  inactive:
    enabled: false
    color: "#ff0000"

bar:
  height: "30px"
  position: "top"
  opacity: 1.0
  background: "#20242cc4"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "13px"
  padding: "4px 6px"
  offset_x: 0
  offset_y: 0
  border_radius: 0
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_center:
    - type: "window title"
  components_right:
    - type: "system tray"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "yyyy.MM.dd HH:mm"

workspaces:
  - name: "1"
    display_name: "Left"
    bind_to_monitor: 2
  - name: "2"
    display_name: "Main"
    bind_to_monitor: 1
  - name: "3"
    display_name: "Right"
    bind_to_monitor: 3
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
  - name: "0"
  - name: "t"
    display_name: "Terminal"
    bind_to_monitor: 3
  - name: "ob"
    display_name: "Obsidian"
    bind_to_monitor: 3
  - name: "vsc"
    bind_to_monitor: 1
    display_name: "Visual Studio Code"
  - name: "vs"
    bind_to_monitor: 1
    display_name: "Visual Studio 2022"
  - name: "chrome"
    display_name: "Chrome Web Browser"
    bind_to_monitor: 2
  - name: "file"
    display_name: "File Explorer"
    bind_to_monitor: 3
  - name: "every"
    display_name: "Everything"
    bind_to_monitor: 3
    #Workspaces @#

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Do not manage picture-in-picture windows for browsers. Note that the default is for
  # English; change `match_title` to the window's title if you use another language.
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
  - command: "ignore"
    match_process_name: "BandiView"
  - command: "ignore"
    match_process_name: "PowerToys.Peek.UI"
  - command: "set floating"
    match_process_name: "Everything"
    #WindowRules @#

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["J", "Up"]
      - command: "resize height -2%"
        bindings: ["K", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H", "Alt+Left"]
  - command: "focus right"
    bindings: ["Alt+L", "Alt+Right"]
  - command: "focus up"
    bindings: ["OemQuestion+RShiftKey+K", "Alt+Up"]
  - command: "focus down"
    bindings: ["OemQuestion+RShiftKey+J", "Alt+Down"]

  # Move focused window in a given direction.
  - command: "move left"
    binding: "OemQuestion+RShiftKey+Left"
  - command: "move right"
    binding: "OemQuestion+RShiftKey+Right"
  - command: "move up"
    binding: "OemQuestion+RShiftKey+Up"
  - command: "move down"
    binding: "OemQuestion+RShiftKey+Down"

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    bindings: ["RControlKey+Left", "HanjaMode+Left"]
  - command: "resize width +2%"
    bindings: ["RControlKey+Right", "HanjaMode+Right"]
  - command: "resize height +2%"
    bindings: ["RControlKey+Down", "HanjaMode+Down"]
  - command: "resize height -2%"
    bindings: ["RControlKey+Up", "HanjaMode+Up"]

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "OemQuestion+RShiftKey+S"
    #ResizeMode @-#

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "OemQuestion+RShiftKey+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "OemQuestion+RShiftKey+Space"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "OemQuestion+RShiftKey+F"
    #ToggleFloating @#

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "OemQuestion+RShiftKey+M"

  # Close focused window.
  - command: "close"
    binding: "OemQuestion+RShiftKey+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "OemQuestion+RShiftKey+F4"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "OemQuestion+RShiftKey+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec wt"
    bindings: ["RMenu+OemQuestion+T", "HangulMode+OemQuestion+T"]
  - command: "exec C:/Users/creat/AppData/Local/Obsidian/Obsidian.exe"
    bindings: ["RMenu+OemQuestion+O", "HangulMode+OemQuestion+O"]
  - command: "exec code"
    bindings: ["RMenu+OemQuestion+C", "HangulMode+OemQuestion+C"]
  - command: "exec devenv"
    bindings: ["RMenu+OemQuestion+V", "HangulMode+OemQuestion+V"]
  - command: "exec %ProgramFiles%/Google/Chrome/Application/chrome.exe"
    bindings: ["RMenu+OemQuestion+W", "HangulMode+OemQuestion+W"]
  - command: "exec C:/Windows/explorer.exe" 
    bindings: ["RMenu+OemQuestion+F", "HangulMode+OemQuestion+F"]
  - command: "exec Everything" 
    bindings: ["RMenu+OemQuestion+E", "HangulMode+OemQuestion+E"]
    #Exec @#

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "OemQuestion+RShiftKey+T"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+N"
  - command: "focus workspace prev"
    binding: "Alt+P"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    bindings: ["RMenu+1", "HangulMode+1"]
  - command: "focus workspace 2"
    bindings: ["RMenu+2", "HangulMode+2"]
  - command: "focus workspace 3"
    bindings: ["RMenu+3", "HangulMode+3"]
  - command: "focus workspace 4"
    bindings: ["RMenu+4", "HangulMode+4"]
  - command: "focus workspace 5"
    bindings: ["RMenu+5", "HangulMode+5"]
  - command: "focus workspace 6"
    bindings: ["RMenu+6", "HangulMode+6"]
  - command: "focus workspace 7"
    bindings: ["RMenu+7", "HangulMode+7"]
  - command: "focus workspace 8"
    bindings: ["RMenu+8", "HangulMode+8"]
  - command: "focus workspace 9"
    bindings: ["RMenu+9", "HangulMode+9"]
  - command: "focus workspace t"
    bindings: ["RMenu+T", "HangulMode+T"]
  - command: "focus workspace ob"
    bindings: ["RMenu+O", "HangulMode+O"]
  - command: "focus workspace vsc"
    bindings: ["RMenu+C", "HangulMode+C"]
  - command: "focus workspace vs"
    bindings: ["RMenu+V", "HangulMode+V"]
  - command: "focus workspace chrome"
    bindings: ["RMenu+W", "HangulMode+W"]
  - command: "focus workspace file"
    bindings: ["RMenu+F", "HangulMode+F"]
  - command: "focus workspace every"
    bindings: ["RMenu+E", "HangulMode+E"]
    #FocusWorkspace @#

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "Alt+Shift+H"
  - command: "move workspace right"
    binding: "Alt+Shift+L"
  - command: "move workspace up"
    binding: "Alt+Shift+K"
  - command: "move workspace down"
    binding: "Alt+Shift+J"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    bindings: ["RMenu+RShiftKey+1", "HangulMode+RShiftKey+1"]
  - commands: ["move to workspace 2", "focus workspace 2"]
    bindings: ["RMenu+RShiftKey+2", "HangulMode+RShiftKey+2"]
  - commands: ["move to workspace 3", "focus workspace 3"]
    bindings: ["RMenu+RShiftKey+3", "HangulMode+RShiftKey+3"]
  - commands: ["move to workspace 4", "focus workspace 4"]
    bindings: ["RMenu+RShiftKey+4", "HangulMode+RShiftKey+4"]
  - commands: ["move to workspace 5", "focus workspace 5"]
    bindings: ["RMenu+RShiftKey+5", "HangulMode+RShiftKey+5"]
  - commands: ["move to workspace 6", "focus workspace 6"]
    bindings: ["RMenu+RShiftKey+6", "HangulMode+RShiftKey+6"]
  - commands: ["move to workspace 7", "focus workspace 7"]
    bindings: ["RMenu+RShiftKey+7", "HangulMode+RShiftKey+7"]
  - commands: ["move to workspace 8", "focus workspace 8"]
    bindings: ["RMenu+RShiftKey+8", "HangulMode+RShiftKey+8"]
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["RMenu+RShiftKey+9", "HangulMode+RShiftKey+9"]
  - commands: ["move to workspace t", "focus workspace t"]
    bindings: ["RMenu+RShiftKey+T", "HangulMode+RShiftKey+T"]
  - commands: ["move to workspace ob", "focus workspace ob"]
    bindings: ["RMenu+RShiftKey+O", "HangulMode+RShiftKey+O"]
  - commands: ["move to workspace vsc", "focus workspace vsc"]
    bindings: ["RMenu+RShiftKey+C", "HangulMode+RShiftKey+C"]
  - commands: ["move to workspace vs", "focus workspace vs"]
    bindings: ["RMenu+RShiftKey+V", "HangulMode+RShiftKey+V"]
  - commands: ["move to workspace chrome", "focus workspace chrome"]
    bindings: ["RMenu+RShiftKey+W", "HangulMode+RShiftKey+W"]
  - commands: ["move to workspace file", "focus workspace file"]
    bindings: ["RMenu+RShiftKey+F", "HangulMode+RShiftKey+F"]
  - commands: ["move to workspace every", "focus workspace every"]
    bindings: ["RMenu+RShiftKey+E", "HangulMode+RShiftKey+E"]
    #MoveToWorkspce @#