#!/bin/bash
shopt -s dotglob

get_first_dir() {
  local path=$1
  local first_dir=$(echo $path | cut -d'/' -f1)
  echo $first_dir
}

exclude_dir() {
  path="$1"
  first_dir=$(get_first_dir $path)
  mv $first_dir delete
  mkdir -p "$path"
  mv delete/"$path"/* "$path"
}

exclude_dirs() {
  local path=$1
  while IFS= read -r line
  do
    if [[ ! "$line" =~ ^# ]] && [[ ! -z "$line" ]]; then
      exclude_dir "$line"
    fi
  done < "$path"
}

# Backup destination
backdest=/opt/sysback

# Labels for backup name
distro=arch
type=full

# Check if chrooted prompt.
echo -n "First chroot from a LiveCD.  Are you ready to restore? (y/n): "
read executeback

# Check file name
ls -l /opt/sysback
echo -n "input backup version name: "
read version

backupfile="$backdest/$distro-$type-$version.tar.gz"

# Exclude file location
excdir="/home/bae/Documents"
exclude_file="$excdir/${prog}_exc.txt"

check_file_exist() {
  if [ -f "$1" ]; then
    return 1
  else
    return 0
  fi
}

check_file_exist "$backupfile"
backupfile_exist=$?

if [ $backupfile_exist -eq 1 ] && [ $executeback = "y" ]; then
  cd /
  echo "This job takes a lot of time. please wait for finish."
  mkdir delete
  exclude_dirs $exclude_file
  rm -rf delete
  bsdtar --acls --xattrs -xpzf "$backupfile"
  echo -e "Job finished. \u25A0"
else
  echo -e "The backupfile doesn't exist. \u25A1"
fi
