[env]
TERM = "xterm-256color"

[general]
import = [
  # "C:/Users/creat/AppData/Roaming/alacritty/catppuccin/catppuccin-latte.toml"
  # "C:/Users/creat/AppData/Roaming/alacritty/catppuccin/catppuccin-frappe.toml",
  "C:/Users/creat/AppData/Roaming/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "C:/Users/creat/AppData/Roaming/alacritty/catppuccin/catppuccin-mocha.toml"
]
working_directory = "C:/Users/creat"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
#FontFamily@#ala.pwsh
size = 10.7
#FontSize@#ala.pwsh
builtin_box_drawing = true

[window]
padding = { x = 4, y = 2 }
decorations = "full"
dynamic_padding = true

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }

[terminal]
shell = "C:/Program Files/PowerShell/7/pwsh.exe"

[keyboard]
bindings = [
  # to unset default keybinding
  { key = "Insert", mods = "Shift", action = "None" },
  { key = "M", mods = "Shift|Control", mode = "~Search", action = "ToggleViMode" }
  #KeyBindings@#ala.pwsh
]