#!/bin/bash
shopt -s dotglob

exclude_dir() {
  path="$1"
  mkdir -p "$path"
  mv delete/"$path"/* "$path"
}

exclude_dirs() {
  local path=$1
  while IFS= read -r line
  do
    if [[ ! "$line" =~ ^# ]] && [[ ! -z "$line" ]]; then
      exclude_dir "$line"
    fi
  done < "$path"
}

#move_to_delete() {
#  local exclude_path=$1
#  # It's so so so dangerous command!! dont do it !
#  mkdir delete
#  mv * delete
#  cp delete/$exclude_path .
#  exc_file=$(basename $exclude_path)
#  exclude_dirs $exc_file
#}

# Backup destination
backdest=/mnt/opt/sysback

# Labels for backup name
distro=arch
type=full

# Check file name
ls -l /mnt/opt/sysback
echo -n "input backup version name: "
read version

backupfile="$backdest/$distro-$type-$version.tar.gz"

# Exclude file location
excdir="/mnt/home/bae/Documents"
exclude_file="$excdir/arch_backup_exc.txt"

check_file_exist() {
  if [ -f "$1" ]; then
    return 1
  else
    return 0
  fi
}

check_file_exist "$backupfile"
backupfile_exist=$?

if [ $backupfile_exist -eq 1 ]; then
  cd /mnt
  echo "This job takes a lot of time. please wait for finish."
  move_to_delete $exclude_file
  pv "$backupfile" | pbzip2 -dc | bsdtar --acls --xattrs -xpzf -
  rm -rf delete
  echo -e "Job finished. \u25A0"
else
  echo -e "The backupfile doesn't exist. \u25A1"
fi
