import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[window.padding]
x = 0
y = 0

[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
