#!/bin/bash
#mount --mkdir /dev/Files/root /mnt/root
#cd /mnt/root/
#./init_live

if [ "$1" = "1" ]; then
  # mount sys_back
  echo "mount Files/sys_back partition"
  mount --mkdir /dev/Files/sys_back /mnt/sys_back

  echo "mount home partition"
  mount /dev/Files/home /mnt/root/home

  setfont ter-u18b.psf.gz -m 8859-2
  echo "console font set."

  iwctl station wlan0 connect SK_WiFiGIGAD61C_5G
  echo "wifi connected."

  echo "Finding fastest mirror server lists."
  echo "This job take a lot of time. Wait for finish."
  reflector -c "South Korea" -a 12 --sort rate \
  --save /etc/pacman.d/mirrorlist
  echo "Job finished."

  timedatectl set-ntp true
  timedatectl set-timezone Asia/Seoul
  echo "timezone set."

  pacman-key --init
  pacman-key --populate archlinux
  pacman -Sy neovim pbzip2 git curl tmux zsh
  echo "neovim, pbzip2, git, curl, tmux zsh installed."
fi
if [ "$1" = "2" ]; then
  cd
  mkdir -p .config/nvim
  cd .config/nvim
  git clone https://github.com/createsejin/nvimt .
  echo "nvimt git cloned."

  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  echo "vim-plug installed."

  cd
  mkdir -p .config/tmux
  cd .config/tmux
  ln -s -r ../nvim/tmux.conf tmux.conf 
  echo "tmux.conf file linked."

  cd
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  echo "tpm installed"

  tmux source-file ~/.config/tmux/tmux.conf
  echo "tmux.conf sourced."
fi

if [ "$1" = "3" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  echo "oh-my-zsh installed."
fi
if [ "$1" = "4" ]; then
  cd
  rm .oh-my-zsh/themes/xiong-chiamiov-plus.zsh-theme
  cd .oh-my-zsh/themes
  ln -s -r ../../.config/nvim/xiong-chiamiov-plus.zsh-theme xiong-chiamiov-plus.zsh-theme
  echo "my custom xiong-chiamiov-plus.zsh-theme linked."

  cd
  ln -s -r .config/nvim/.zshrc .zshrc
  source .zshrc
  echo ".zshrc sourced."

  echo -e "All jobs done. \u25A0"
  echo -e "\nYou should install tmux plugins and nvim plugins inside respective programs."
fi
